### ISSUE TITLE
Follow HTTP 503 and 'Retry-After' header

### ISSUE THREAD

**Issue by krateng** [verlok/vanilla-lazyload#593] opened 2023-04-01 14:59 UTC
When an image fetch returns an error, lazyload will mark that element as failed. If the error is [503 Service Unavailable](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503) and contains a [Retry-After](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After) header field, could it instead follow that header and retry fetching the image after the specified time?

**Comment by verlok** [comment] 2023-04-01 17:22
Good question, is it possible to read that content from the header in JS?

**Comment by verlok** [comment] 2023-04-02 04:14
If yes, that would be possible. This LazyLoad script already gave the ability to retry on networks errors, when the internet is failing, on the “back online” event.

**Comment by krateng** [comment] 2023-04-02 12:21
I don't know how lazyload sends its request, but e.g. for goold old `XMLHttpRequest` it's possible with `getResponseHeader()`.

**Comment by verlok** [comment] 2023-04-02 13:45
The problem is that this script doesn’t send any request, just changes the images DOM, so there is no way to see the headers of the responses

**Comment by verlok** [comment] 2023-04-02 13:45
I’m closing this as this isn’t feasible

**Closed by verlok** 2023-04-02 13:45 UTC
Labels: TYPE: Enhancement
