### ISSUE TITLE
Investigate Safari 15.4 + hybrid lazy loading

### ISSUE THREAD

**Issue by Bjornftw** [verlok/vanilla-lazyload#563] opened 2022-03-23 09:29 UTC
**Describe the bug**
With the latest Safari (15.4>) the `data-src` image won't show anymore. I think the problem is the `loading="lazy"` is blocking the replaced images. Lazy loading is working in Safari since this release.

**To Reproduce**
1. Go to https://cardmapr.nl on Safari 15.4 or newer
2. Click on see the blurry images on the homepage

**Expected behavior**
`data-src` should be showed even when the default lazy loading is enabled.

**LazyLoad version**
Please report which version of LazyLoad you're using.
- Version 17.6.1

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Macbook & iPhone 13 Pro
 - OS: MacOS 12.3 and iOS 15.4
 - Browser: Safari
 - Version 15.4

**Screenshots**
![Screenshot 2022-03-23 at 10 28 46](https://user-images.githubusercontent.com/2643275/159667179-79eb9565-45c7-441e-b185-e16ebae03736.png)

**Comment by verlok** [comment] 2022-03-23 14:12
Hey @Bjornftw ,
thanks for reporting this.

I've just checked on the demos and it seems everything works as expected.

<img width="580" alt="Screenshot 2022-03-23 at 15 09 58" src="https://user-images.githubusercontent.com/1127721/159719159-b4f11c5f-38ac-4d24-8902-f09b19b1d723.png">

Would you be able to report some of your HTML+JS code here or isolate the problem on a codepen?

**Comment by verlok** [comment] 2022-03-23 14:20
In addition, I see that in the website you mentioned, the images is correctly loaded in the `src` attribute. 

<img width="1017" alt="Screenshot 2022-03-23 at 15 18 44" src="https://user-images.githubusercontent.com/1127721/159720854-5855e4dc-893d-4ad9-b588-13693b830b69.png">

Are you sure you're not hiding the fully loaded image with your JS or CSS?

**Comment by verlok** [comment] 2022-03-23 14:21
And the [loaded image](https://cdn.cardmapr.nl/categories/restaurant.jpg?w=414&h=180&fit=crop) responded correctly with a 200 response.

**Comment by Bjornftw** [comment] 2022-03-23 14:22
@verlok Did you set `loading="lazy` on the images?

https://codepen.io/bjornftw/pen/ZEvBrqq
Works on Chrome, but not on Safari.

**Comment by Bjornftw** [comment] 2022-03-23 14:41
Yes, we added "loading="lazy"` on all images because Google is crying about optimisation. Chrome can handle it, but Safari can't handle both (loading lazy and vanilla-lazyload). Since Safari 15.4 (desktop AND mobile) we saw these unloaded images.

When we delete `loading="lazy"` from all images the problem is solved, but maybe is there a other solution so we can still use the default browser tag.

**Comment by verlok** [comment] 2022-03-23 14:46
I get it. 
The fix is in the link I provided above. 


I will investigate further on the issue, but I’m afraid if it depends on the browser there’s not much I can do.

**Comment by verlok** [comment] 2022-04-09 15:55
I finished the investigation, @Bjornftw 

My script copies the attribute value from `data-src` to `src` as expected, but Safari ignores the new value of `src` for some reason.

Following a screenshot of the inspector open with the new `src` set to high res photo and safari still showing the low res one.

![image](https://user-images.githubusercontent.com/1127721/162581518-a4cadeb3-f24c-401a-a6b2-98a191d33c80.png)

So it's definitely a Safari bug. 

I will report it to Apple immediately, and hopefully they will fix it in one of the next versions.

In the meantime, I hope you found my hybrid [lazy loading article](https://www.smashingmagazine.com/2019/05/hybrid-lazy-loading-progressive-migration-native/) useful.

Did you?

**Comment by verlok** [comment] 2022-04-09 16:03
Hey again @Bjornftw 
I hope this investigation and the bug sent to Apple solves your issue.

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation. Or [sponsor me](https://github.com/sponsors/verlok), if you're a fan.

Open-source software is great for everyone, but it takes passion and time (and coffee!) to grow and evolve.

Thank you for thinking about it. 
Have a wonderful day!

**Comment by DahmaniAdame** [comment] 2023-10-02 05:05
The issue is still there. Safari didn't do much to sort it out 😅
Jetpack seems to have found [the root cause](https://github.com/Automattic/jetpack/pull/29243) and a hack to prevent it: https://github.com/Automattic/jetpack/blob/trunk/projects/packages/lazy-images/src/js/lazy-images.js#L183-L188

**Comment by verlok** [comment] 2023-10-02 06:56
Thanks @DahmaniAdame, I'll give it a look.

**Comment by verlok** [comment] 2023-10-02 09:59
Ok @DahmaniAdame, I took a look and I've read this conversation again.

The Safari bug is that it doesn't load the new images declared in `src` or `srcset` when the value of that attribute is changed after some time, when the image is marked as `loading=lazy`.

This bug causes problems when the technique used by the front-end is to load a low-res image as a placeholder, while the full-res image is being loaded in the background.

So you're suggesting to recreate the image's DOM using the trick to force Safari to re-parse the image.

```js
image.outerHTML = image.outerHTML;
```

I'm thinking... why in the first place the front-end would load the low-res image if the browser can already manage lazy loading of the full-res image?

**Comment by verlok** [comment] 2023-10-02 10:09
@DahmaniAdame let me reformulate the question.

Browser-native lazy loading allows the front-end to directly lazy load the high-res image, like:

```html
<img src="high-res.webp" loading="lazy">
```

So why should the front-end do something like the following?

```html
<img src="low-res.webp" loading="lazy" data-src="high-res.webp">
```

I can understand this could be to show some kind of low-res image and swap the image to a high-res image when the image enters the viewport, BUT, this technique heavily relies on JS and should be used ONLY with JS-driven lazy loading, such as the one that this library can do, and NOT to be mixed with browser-driven (native) lazy loading.

So, the frontend should choose if to go for the JS-driven approach (and have the effect of swapping the resolution on enter) OR for the native approach.

JS-driven:

```html
<img src="low-res.webp" class="lazy" data-src="high-res.webp">
```

Native:

```html
<img src="high-res.webp" loading="lazy">
```

I don't see the point or the advantage of having a mixed situation, which might cause bugs (and it's causing bugs) on different browsers implementations.

I'm open to discussion if you can convince me of the opposite.

**Comment by verlok** [comment] 2023-10-02 10:10
@DahmaniAdame we commented almost simultaneously, please read my latest comment just before yours.

**Comment by DahmaniAdame** [comment] 2023-10-02 11:46
@verlok fair point. 
I was thinking of cases where both lazyload end up on an implementation. But that should be prevented on the implementation side. 
Thanks for having a look. 
Feel free to close this issue as I don't see any value of adding the hack for Safari.

**Closed** 2023-10-02 13:07 UTC
Labels: TYPE: Question
