### ISSUE TITLE
class_[applied|loading|loaded|error] config options are additive, and don't change the default setting

### ISSUE THREAD

**Issue by fienen** [verlok/vanilla-lazyload#470] opened 2020-07-01 14:04 UTC
**Describe the bug**
When trying to change the default classes used by the object, if you set one of the `class_*` values, those values get added to what's used, rather than replacing them. For instance `class_loading: 'lazy-loading'` results in the DOM element getting BOTH the new `lazy-loading` class AND the original `loading` class. 

**To Reproduce**
1. Create a new LazyLoad object
2. Set config values for any of the class_* parameters
3. Load a page and inspect the classes as they change through steps on the DOM element
4. Note that the newly configured class is added, but is in addition to the default, not in replace of it.

**Expected behavior**
Setting new config values for `class_*` parameters should overwrite the default, not extend them.

**LazyLoad version**
Please report which version of LazyLoad you're using.
- Version 17.0.1

**Desktop (please complete the following information):**
 - OS: Windows 10, Ubuntu 20.04 (likely any)
 - Browser: Firefox, Chrome (likely any)
 - Version: latest on both as of current date

**Smartphone (please complete the following information):**
Not tested

**Screenshots**
![image](https://user-images.githubusercontent.com/784502/86252339-b4ae1a80-bb78-11ea-823d-e2f23e4d9c8f.png)

**Additional context**
I feel like maybe this is actually intentional, but it feels very problematic for anyone trying to prevent styling collisions with commonly used class names like "loading" or "loaded." Usually when using a JS tool that takes custom settings, it's typical that the setting overrides the default.  If it's determined that this is a "won't fix" situation, I might suggest adding clarification to the documentation on the parameters to make it clear that changing the setting will only add the new classes and not override the default.

**Comment by verlok** [comment] 2020-07-01 22:27
Hey @fienen,
thanks for reporting. 

It's not intentional, it's a bug. 
I'm on it.

**Comment by verlok** [comment] 2020-07-01 22:35
I've just tried

```js
var ll = new LazyLoad({
  class_applied: "lz-applied",
  class_loading: "lz-loading",
  class_loaded: "lz-loaded",
  class_error: "lz-error"
});
```

But I'm not able to reproduce it. 
Look at the classes that have being applied.

![image](https://user-images.githubusercontent.com/1127721/86297359-668e2b00-bbfb-11ea-820d-24be1a8119c3.png)

![image](https://user-images.githubusercontent.com/1127721/86297458-ae14b700-bbfb-11ea-8324-802b54901d7d.png)

![image](https://user-images.githubusercontent.com/1127721/86297513-d69cb100-bbfb-11ea-992c-25785be27ed4.png)

![image](https://user-images.githubusercontent.com/1127721/86297533-e4523680-bbfb-11ea-8ec3-2e7211114203.png)

Are you absolutely sure it's not something on your side that apply those classes?

**Comment by verlok** [comment] 2020-07-03 19:29
@fienen any feedback?

**Comment by verlok** [comment] 2020-07-11 05:43
I suppose you solved. Closing this. Feel free to reopen if you still need help.

**Closed** 2020-07-11 05:43 UTC
Labels: STATUS: Awaiting feedback, TYPE: Bug
